---
- name: Ensure dotfiles repository is cloned locally.
  git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ dotfiles_repo_local_destination }}"
    version: "{{ dotfiles_repo_version }}"
    accept_hostkey: "{{ dotfiles_repo_accept_hostkey }}"
  become: false

- name: Check if submodules are in use
  stat:
    path: "{{ dotfiles_repo_local_destination }}/.gitmodules"
  register: result
  become: false

- name: Update submodules if needed
  command: "cd {{ dotfiles_repo_local_destination }} && git submodule update --init"
  when: result.stat.exists
  become: false

- name: Ensure all configured dotfiles are links.
  command: "ls -F {{ dotfiles_home }}/{{ item }}"
  register: existing_dotfile_info
  failed_when: false
  check_mode: false
  changed_when: false
  loop: "{{ dotfiles_files }}"
  loop_control:
    label: "{{ [item] }}"

- name: Remove existing dotfiles file if a replacement is being linked.
  file:
    path: "{{ dotfiles_home }}/{{ item.item }}"
    state: absent
  when: "item.rc == 0"
  loop: "{{ existing_dotfile_info.results|flatten(levels=1) }}"
  loop_control:
    label: "{{ [item.item] }}"

- name: Create required folders in home folder.
  file:
    path: "{{ dotfiles_home }}/{{ item }}"
    state: directory
    mode: "u=rwX,g=rX,o=rX"
  become: false
  loop: "{{ dotfiles_folders }}"

- name: Link dotfiles into home folder.
  file:
    src: "{{ dotfiles_repo_local_destination }}/{{ item }}"
    dest: "{{ dotfiles_home }}/{{ item }}"
    state: link
    mode: "u=rwX,g=rX,o=rX"
  become: false
  loop: "{{ dotfiles_files }}"

- name: Link special dotfiles into home folder.
  file:
    src: "{{ dotfiles_repo_local_destination }}/{{ item.src }}"
    dest: "{{ dotfiles_home }}/{{ item.dest }}"
    state: file
    mode: "u=rwX,g=rX,o=rX"
  become: false
  loop: "{{ dotfiles_special_links|flatten(levels=1) }}"
